### PR TITLE
added License

### PR DESCRIPTION
**Pull request by barryWhiteHat**
added License

### CODE REVIEW

**Comment by barryWhiteHat** [comment]
@vaibhavchellani @therealyingtong @GuthL @tspoff 

Can you all sign off that its okay to use this license for our previous and future work on rollupNC.

**Comment by vaibhavchellani** [comment]
@barryWhiteHat looks good to me :)

**Comment by therealyingtong** [comment]
i'm good with this!

**Comment by onyb** [comment]
The GPLv3 may not be the best license for the future use-cases of RollupNC. The GNU General Public License permits making a modified version and letting the public access it on a server without ever releasing its source code to the public.

I would therefore like to make a case for the **GNU Affero General Public License v3**. Think of it as GPLv3 with the following additional condition:

> When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.

Here is an easy to understand version of the license: https://choosealicense.com/licenses/agpl-3.0

**Comment by barryWhiteHat** [comment]
Sure i am happy with that. @therealyingtong @vaibhavchellani  ?

**Comment by GuthL** [comment]
I agree to the licence

**Comment by fredlacs** [comment]
Works for me!

**Comment by tspoff** [comment]
Works for me.

**Comment by vaibhavchellani** [comment]
Works for me 👍

**Pull request merged**
